%YAML:1.0
---
mode: 1 #2 测试点云box与box32互转 3  点云转TSDF  4 tsdf转点云  5读取tsdf
save_skip_list_num: 800  #2 load
# matpose: /home/u20/dataset/loop/
# matpose: /home/u20/dataset/paper/f2_pioneer_360/
#985 grids
# matpose: /home/u20/dataset/paper/rgbd_dataset_freiburg1_desk/
# matpose: /home/u20/dataset/paper/f3_nostructure_texture_near_withloop/
# matpose: /home/u20/dataset/paper/f1_desk/ #139 complete_kitchen
#12112 f3_long_office breakfast_room morning_apartment complete_kitchen
# matpose: /home/u20/dataset/paper/3
#  f2_pioneer_360
# matpose: /dataset/dataset/nerf/green_room
# kitchen" 
# grey_white_room"
# matpose: "/home/u20/dataset/code/U-V-disparity/viz_elas_setero/build"
# matpose: "/home/u20/dataset/00"
matpose: "/home/u20/dataset/paper/f2_pioneer_360"
show_cloud: 1
#True
